### ISSUE TITLE
0.7.1 fails to start

### ISSUE THREAD

**Issue by devastgh** [Ride-The-Lightning/c-lightning-REST#114]
I'm using c-lightning-REST as a plugin, and since i did not want to restart my node, i simply stopped the 0.7.0 plugin, and started the 0.7.1. However 0.7.1 fails to start, the error message is the following:

 lightning-cli plugin start /home/lightning/.lightning/plugin/c-lightning-REST/plugin.js
{
   "code": -3,
   "message": "/home/lightning/.lightning/plugin/c-lightning-REST/plugin.js: Unknown log-level \"--- Starting the cl-rest server ---\", valid values are \"debug\", \"info\", \"warn\", or \"error\"."
}

Starting 0.7.0 with the same command line (lightning-cli plugin start) works.

The plugin might start ok if i restart my node, but currently i cannot do that, maybe later in the evenging i will have some time to do it, and i'll update this ticket.

**Comment by blckbx** [comment]
Can confirm this. Running plugin.js as a plugin through CLN's config throws said error:
```
2022-05-09T13:46:20.021Z UNUSUAL plugin-plugin.js: Killing plugin: Unknown log-level "--- Starting the cl-rest server ---", valid values are "debug", "info", "warn", or "error".
```
Spinning it up separately via `node cl-rest.js` works fine.

**Comment by saubyk** [comment]
> Starting 0.7.1 with "node /full/path/to/cl-rest.js" works. My node.js is installed from snap, if that makes a difference.

Hi @devastgh have you run `npm install --only=prod` before starting the server?

**Comment by saubyk** [comment]
> Can confirm this. Running plugin.js as a plugin through CLN's config throws said error:
> 
> ```
> 2022-05-09T13:46:20.021Z UNUSUAL plugin-plugin.js: Killing plugin: Unknown log-level "--- Starting the cl-rest server ---", valid values are "debug", "info", "warn", or "error".
> ```
> 
> Spinning it up separately via `node cl-rest.js` works fine.

I am able to replicate this as well. Will look into it urgently and issue a hotfix. Thanks

**Comment by devastgh** [comment]
> > Starting 0.7.1 with "node /full/path/to/cl-rest.js" works. My node.js is installed from snap, if that makes a difference.
> 
> Hi @devastgh have you run `npm install --only=prod` before starting the server?

Yes, i did. It might have to do with my nodejs, as it's installed on ubuntu as a snap ( classic snap, so not restricted).

**Comment by saubyk** [comment]
fixed with https://github.com/Ride-The-Lightning/c-lightning-REST/commit/7b9b7d4b841863876aa9c112318d04e7aa06ee90

Tagging a new release version.
