### ISSUE TITLE
Add subscription to `waitblockheight`, `waitinvoice` and `waitsendpay` RPC commands

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/c-lightning-REST#127]
Add subscription to `waitblockheight`, `waitinvoice`, `waitanyinvoice` and `waitsendpay` RPC commands.

Reference PR: https://github.com/Ride-The-Lightning/c-lightning-REST/pull/85

**Comment by saubyk** [comment]
Closed with release v0.7.3
