### ISSUE TITLE
"Empty reply from server"

### ISSUE THREAD

**Issue by AngeloMetal** [Ride-The-Lightning/c-lightning-REST#132]
Hello, I ran ``curl -X GET "http://localhost:3001/v1/getBalance" -H  "accept: application/json"`` to try out C-Lightning-REST, but I get:
```curl: (52) Empty reply from server```

Node js version: ``v14.16.1``
I'm running a Lightning node normally by the way.

**Comment by ShahanaFarooqui** [comment]
1: Please ensure that the url is correct? This request should get the authentication error in response.
2: This API expects base64 macaroon value in header.
3: Are you getting any response from ‘getInfo’ API?

**Comment by AngeloMetal** [comment]
> 1: Please ensure that the url is correct? This request should get the authentication error in response.

I visit ``http://192.168.2.5:3001/v1/getBalance`` (which is the local IP address) from another computer and get this:
```
The connection was reset

The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
```

> 2: This API expects base64 macaroon value in header.

The API from where? ``http://192.168.2.5:4001/api-docs/``? That "Authorize" button?

> 3: Are you getting any response from ‘getInfo’ API?

``/getinfo``? No.

**Comment by ShahanaFarooqui** [comment]
1: Please try getinfo api first with GET endpoint at `https://192.168.2.5:3001/v1/getInfo`. 
2: You also need to send `macaroon` header in Base64. Default location for the `access.macaroon' is in c-lightning-REST/certs. You can get Base64 access.macaroon value with ` base64 c-lightning-REST/certs/access.macaroon` command.

So your final curl query should be similar to:
`curl -X 'GET' 'https://192.168.2.5:3001/v1/getinfo' -H 'accept: application/json' -H 'macaroon: Ag***DQ=`

**Comment by AngeloMetal** [comment]
> 1: Please try getinfo api first with GET endpoint at ``https://192.168.2.5:3001/v1/getInfo``.

I get: ``{"message":"Authentication Failed!","error":"Bad Macaroon!"}``, which is what I should get. 

> So your final curl query should be similar to

I enter ``curl -X 'GET' 'https://localhost:3001/v1/getinfo' -H 'accept: application/json' -H 'macaroon: Ag[...]l4='``

And get:
```
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by ShahanaFarooqui** [comment]
If you are running it in the browser then you have to disable ssl certificate check like below:
https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate
https://stackoverflow.com/questions/20088/is-there-a-way-to-make-firefox-ignore-invalid-ssl-certificates

If you are using curl then use --insecure flag to disable TLS cert validity check.
https://curl.se/mail/archive-2017-04/0002.html#:~:text=The%20%2Dk%2C%20%2D%2Dinsecure%20flag,the%20validity%20of%20TLS%20certificates%22.

**Comment by AngeloMetal** [comment]
Thanks, it now works. 

However, I don't think this satisfies my occasion. I want to get invoice from other peoples' nodes and deliver it to my web page. For example, client connects to my server, my server queries your invoice from your server, I get the invoice, I give your invoice to my client. I'm afraid this isn't possible, because I need other people's ``access.macaroon`` file which is meant to be private. 

But, it just doesn't make sense. Why would I want such private file for letting me have your invoice?

**Comment by ShahanaFarooqui** [comment]
This question is more relevant for Core Lightning telegram channel. You should learn more about offers (bolt12 invoices).

closing the issue now. Thanks.
