### ISSUE TITLE
Authentication troubleshooting

### ISSUE THREAD

**Issue by bleebl33** [Ride-The-Lightning/c-lightning-REST#147]
My access.macaroon from cl-rest works for RTL, but I'm getting auth failure when I try to add lightningd to Zeus with the hex string, with or without base64. Any advice? 

```bash
curl -H "macaroon:$(base64 access.macaroon)" http://127.0.0.1:3001/v1/getinfo/
{"message":"Authentication Failed!","error":"Bad Macaroon!"}

curl -H "macaroon:$(xxd -ps -u -c 256 access.macaroon)" http://127.0.0.1:3001/v1/getinfo/
{"message":"Authentication Failed!","error":"Bad Macaroon!"}
```

**Comment by bleebl33** [comment]
Finally found my way there:

```bash
curl -H "macaroon:$(base64 -w0 access.macaroon)" http://127.0.0.1:3001/v1/getinfo/
```

I'm still confused why the HEX string authentication didn't work, but base64 is fine too.

**Comment by ShahanaFarooqui** [comment]
`Base64` is default encoding type for macaroon authentication. To authenticate with `HEX` macaroon value, an additional header `encodingtype` is required: 

`curl -k -H "encodingtype:hex" -H "macaroon:$(xxd -ps -u -c 256 access.macaroon)" https://127.0.0.1:3001/v1/getinfo`
