### ISSUE TITLE
[Feature Request] Pay endpoint to support maxfee option

### ISSUE THREAD

**Issue by newtonick** [Ride-The-Lightning/c-lightning-REST#160]
Core Lightning pay on bolt11 supports an option for maxfee. Would it be possible for the pay endpoint to add an option for max fee?

https://lightning.readthedocs.io/lightning-pay.7.html

**Comment by saubyk** [comment]
sure can do. tagged it for the next release milestone.

Feel free submit a pr if you'd like

**Comment by saubyk** [comment]
address with https://github.com/Ride-The-Lightning/c-lightning-REST/commit/a3467da26b9f249d30c4d399809de7bebbbff63b
