### ISSUE TITLE
Cannot set fees on cln 23.02

### ISSUE THREAD

**Issue by devastgh** [Ride-The-Lightning/c-lightning-REST#162]
Cannot set fees on cln 23.02.

`setchannelfee` has been deprecated in 0.11.xxx and it has been removed from 23.02. Use `setchannel` instead.

**Comment by saubyk** [comment]
addressed with https://github.com/Ride-The-Lightning/c-lightning-REST/commit/e80c0243b42dc9b4687ccbc6d76c5651e9459b42
