### ISSUE TITLE
POST /v1/rpc not working

### ISSUE THREAD

**Issue by polespinasa** [Ride-The-Lightning/c-lightning-REST#166]
Hi,

I don't know if I'm doing something wrong with the petition, but I'm getting an error when I try to make a POST petition to /v1/rpc.
![image](https://user-images.githubusercontent.com/57642229/228662468-34c6f4f2-6ada-4444-9076-ca7869ac4c9e.png)

Please also see the same command with verbose for more details:

![image](https://user-images.githubusercontent.com/57642229/228662908-9b2ee2ea-a196-444a-95a0-9031fe11a06c.png)

I know I can do the same petition "getInfo" by using GET petition on "/v1/getinfo". I need to execute some specific RPC commands to my node and I'm trying with this one just for testing.

The macaroon is well configured as other petitions as "/v1/getinfo" are working. It's just the /rpc that it's not.

Thanks in advance for your help,
Pol

**Comment by ShahanaFarooqui** [comment]
@polespinasa Have you set `"RPCCOMMANDS": ["*"]` in your cl-rest-config.json?

**Comment by polespinasa** [comment]
> @polespinasa Have you set `"RPCCOMMANDS": ["*"]` in your cl-rest-config.json?

Hi @ShahanaFarooqui I have found another way to do what I need without this REST query.
Anyway many thanks for your swift answer.
