### ISSUE TITLE
Channel Data Broken with CLN v23.05

### ISSUE THREAD

**Issue by 21M4TW** [Ride-The-Lightning/c-lightning-REST#175]
This plugin appears to be broken when used with CLN v23.05. The plugin reports channel balances of 0. It affects projects that depend on the plugin such as RTL and Zeus. This person here experiences the issue as well: https://github.com/ZeusLN/zeus/issues/1464 . My understanding is that CLN's interface has changed a bit regarding channel data.

**Comment by ShahanaFarooqui** [comment]
It has already been addressed. Code has been updated in Release 0.10.3 branch and testing is 90% done.
Duplicate: https://github.com/Ride-The-Lightning/c-lightning-REST/issues/168
