### ISSUE TITLE
Feature request: allow `listPays` and `listInvoices` to use `payment_hash`

### ISSUE THREAD

**Issue by callebtc** [Ride-The-Lightning/c-lightning-REST#184]
Thank you for working on this project!

`listPays` and `listPay` needs the bolt11 invoice, whereas `listInvoices` requires the CLN "label". This is kinda inconsistent and also not what most backends would want to use I suppoe. Instead, both methods should ideally allow all common options (label, bolt11, payment hash) to look up entries but in particular the `payment_hash` would be very useful. 

I have do do some serious yoga in order to make it work with LNbits because of this. Would be nice to add support for these params in the API (since the cln interface already supports this).

**Comment by ShahanaFarooqui** [comment]
@callebtc Thank you for raising the issue. 

These features have been added with PR #185 in `Release-v0.10.5` branch. Closing the issue now.
