### ISSUE TITLE
Error to Set Enable 2FA in RTL 0.014 and API-REST 0.10.3

### ISSUE THREAD

**Issue by soyishikawa** [Ride-The-Lightning/c-lightning-REST#194]
When i try to set Set Enable 2FA i got this error.

![Error 2FA RTL](https://github.com/Ride-The-Lightning/c-lightning-REST/assets/46906582/bcfe3a7c-6df2-4c6e-91b8-a82d44839757)

Do not recognize de Code generated.  

Version RTL and API-REST

![Error 2FA RTL 2](https://github.com/Ride-The-Lightning/c-lightning-REST/assets/46906582/0a676af3-1207-48ee-bc45-406015a55567)

Please try to solve this problem.

Thansk you

**Comment by ShahanaFarooqui** [comment]
The issue is not related to c-lightning-REST or RTL and cannot be solved by us. Token and secret has to be correct for RTL to enable 2FA.
