### ISSUE TITLE
getBalance does not work with core-lightning version above 23.02

### ISSUE THREAD

**Issue by enaples** [Ride-The-Lightning/c-lightning-REST#195]
I've  been testing the [wallets/clnrest](https://github.com/lnbits/lnbits/tree/wallets/clnrest) branch of lnbits and I noted that on [line 45](https://github.com/Ride-The-Lightning/c-lightning-REST/blob/29de0b08613d4f7866e2c604d09ce25c690bc118/controllers/getBalance.js#L45) 
```
const versionCompatible = global.version && isVersionCompatible(global.version, '23.02');
```

of the getBalance controller there is something that prevents `/v1/getBalance` route from returning the correct balance if the core-lightning version is  above 23.02 (I am using the latest 23.05.2). 
This in turn causes lnbits's clnrest backend to fail and keep disconnecting.

I have investigated further (i.e., `v1/getinfo`) and it does not seem to have the same version check. Is there a reason for this choice? Is there some breaking changes regarding [listfunds](https://docs.corelightning.org/reference/lightning-listfunds) RPC call?

**Comment by ShahanaFarooqui** [comment]
This is not a bug which should/can be fixed. The response has been changed at core lightning, so we had to add version check to keep these APIs backward compatible.
