### ISSUE TITLE
No onchain & lightning balance shown in RTL & Zeus

### ISSUE THREAD

**Issue by teemie1** [Ride-The-Lightning/c-lightning-REST#197]
My environment:
 - OS: Ubuntu 22.04.2 LTS
 - Bitcoin Core 25.0
 - Core Lightning 23.05.2
 - c-lightning-REST v0.10.5
 - RTL 0.14.0
 - Zeus on my iPhone 0.7.7
Problem:
  I installed CLN 23.05.2 with cln-rest plugin v0.10.5, RTL 0.14.0 . After I transfer fund to my on chain address of CLN. RTL did not show on chain balance and I could not open channel via RTL. In "lightning-cli listfunds" command show balance. I used lightning-cli fundchannel to open channel successfully. Then all lightning & on chain balance still be 0 in RTL. When I connect via Zeus, it is the same problem. Anyone have an idea for this.

![image](https://github.com/Ride-The-Lightning/c-lightning-REST/assets/92665293/933fc0d5-f4b6-4ea1-a663-ef1bd74a968b)

**Comment by ShahanaFarooqui** [comment]
@teemie1 Thank you for reporting the issue but I am unable to reproduce it locally. I tested it on the same stack and getting correct balances. 

![Screenshot from 2023-08-14 12-32-46](https://github.com/Ride-The-Lightning/c-lightning-REST/assets/23240721/6f4a789a-0806-4169-a5da-be9d0a8279dd)

**Comment by teemie1** [comment]
Thank you for your response. I devided to reinstall all of them because of my hardware failure. I’ll update the result when it’s finished.

**Comment by zagota** [comment]
have the same problem. The output of
```
journalctl -f -u c-lightning-REST
```
is
```
.... node[43477]: warn: Invalid Version String
.... node[43477]: warn: Invalid Version String
```

**Comment by ShahanaFarooqui** [comment]
> have the same problem. The output of
> 
> ```
> journalctl -f -u c-lightning-REST
> ```
> 
> is
> 
> ```
> .... node[43477]: warn: Invalid Version String
> .... node[43477]: warn: Invalid Version String
> ```

Are you calling c-lightning-REST's `listpeerchannels` api without calling `getinfo`? Or are you running any non-released version on CLN?

**Comment by zagota** [comment]
> 
> Are you calling c-lightning-REST's `listpeerchannels` api without calling `getinfo`? Or are you running any non-released version on CLN?

Hello, 
i am not a developer. 
This message appears when I start Zeus Wallet.
Since a few days CLN "23.08" is running.

**Comment by ShahanaFarooqui** [comment]
Version string "23.08" will throw the error message as c-lightning-REST expects the version string to start with "v". So the valid version string should be "v23.08".

**Comment by ShahanaFarooqui** [comment]
Updated the code to allow a version string with or without "v" prefix. Will be release with v0.10.6
