### ISSUE TITLE
native rest-plugin (23.08) and cl-rest not possible to run in parallel?

### ISSUE THREAD

**Issue by btchans** [Ride-The-Lightning/c-lightning-REST#198]
when updating to cln to 23.08
i get this on startup:

`error starting plugin '/usr/local/libexec/c-lightning/plugins/clnrest/clnrest.py': option name 'rest-protocol' is already taken`

**Comment by ShahanaFarooqui** [comment]
c-lightning-REST and clnrest intentionally designed to be mutually exclusive. 

You can use CLN's `disable-plugin` to disable `clnrest.py` to avoid any conflict with this one.

**Comment by LeoSpyke** [comment]
@ShahanaFarooqui according to the CLN docs [here](https://docs.corelightning.org/docs/third-party-libraries#rest), the c-lightning-REST will be soon replaced by the clnrest natively built into CLN.
Is there a way to configure RTL to use clnrest directly (I'm referring mainly to new setups)?

**Comment by ShahanaFarooqui** [comment]
c-lightning-REST and clnrest are not compatible, so you cannot directly change the url. However, I am currently working on RTL's migration and it should be ready to use soon.
