### ISSUE TITLE
Listening for paid invoices

### ISSUE THREAD

**Issue by LightningK0ala** [Ride-The-Lightning/c-lightning-REST#20]
Great work on the library! Are there plans to including a websocket to subscribe to invoices that are paid?

**Comment by saubyk** [comment]
Thanks @LightningK0ala 
No plan yet. Will explore this requirement more.

**Comment by darosior** [comment]
@saubyk FWIW now that you support plugin mode you can listen to notifications such as `invoice_payment` ;-) https://lightning.readthedocs.io/PLUGINS.html#invoice-payment

**Comment by Kukks** [comment]
This could help: https://github.com/btcpayserver/BTCPayServer.Lightning/blob/dee2f2809d31ec7681b0b97b96fb7a610993b18e/src/BTCPayServer.Lightning.CLightning/CLightningClient.cs#L418

**Comment by rsbondi** [comment]
You could just run [this](https://github.com/rbndg/c-lightning-events) plugin, there would really be no benefit to including here unless for some reason you are running as a service and can not use plugins?  Of course the plugin is newer than the last comment in this thread so maybe it could be the solution.

**Comment by Kukks** [comment]
We run C-lightning-rest as a standalone service in its own docker container so we cannot have a plugin

**Comment by ShahanaFarooqui** [comment]
It was resolved a while back. Closing it now.
