### ISSUE TITLE
Zeus unable to retrieve channel info after upgrade to v24.05 Core Lightning 

### ISSUE THREAD

**Issue by bitcoinlizard** [Ride-The-Lightning/c-lightning-REST#214]
I believe this call is broken:

"/v1/channel/listChannels/"

I receive this result:

{"error":{}}

**Comment by ShahanaFarooqui** [comment]
The endpoint needs to be updated to `/v1/channel/listPeerChannels/` as CLN updated listChannels and listPeerChannels commands.
