### ISSUE TITLE
Include channel initiator in listChannels

### ISSUE THREAD

**Issue by jamaljsr** [Ride-The-Lightning/c-lightning-REST#24]
I'm running a regtest network with two c-lightning nodes and one channel between the two. When I query `channel/listChannels`, on both nodes I am provided the same channel which is expected. However, I am unable to determine which node opened this channel based on the data returned. 

alice
```
[
    {
        "id": "030baa91a579432ad819a8d175bd69262443a5a7197bfde0a112cf29ff489023be",
        "connected": true,
        "state": "CHANNELD_NORMAL",
        "short_channel_id": "108x1x0",
        "channel_id": "2c029d05f60b7a6073e62f45b487b0935e05f3eb0f9ba24abc5861dcebf686c4",
        "funding_txid": "c486f6ebdc6158bc4aa29b0febf3055e93b087b4452fe673607a0bf6059d022c",
        "private": false,
        "msatoshi_to_us": 250000000,
        "msatoshi_total": 250000000,
        "their_channel_reserve_satoshis": 2500,
        "our_channel_reserve_satoshis": 2500,
        "spendable_msatoshi": 247274000,
        "alias": "bob"
    }
]
```

bob
```
[
    {
        "id": "03e8b189c71cd8346d6afbd773b403e603472339ff190413644b075fab844a9a3b",
        "connected": true,
        "state": "CHANNELD_NORMAL",
        "short_channel_id": "108x1x0",
        "channel_id": "2c029d05f60b7a6073e62f45b487b0935e05f3eb0f9ba24abc5861dcebf686c4",
        "funding_txid": "c486f6ebdc6158bc4aa29b0febf3055e93b087b4452fe673607a0bf6059d022c",
        "private": false,
        "msatoshi_to_us": 0,
        "msatoshi_total": 250000000,
        "their_channel_reserve_satoshis": 2500,
        "our_channel_reserve_satoshis": 2500,
        "spendable_msatoshi": 0,
        "alias": "alice"
    }
]
```

Does c-lightning provide info about which node initiated the channel opening that could then be made available in this REST api? LND includes an `initiator` boolean for each channel it returns via RPC.

I am making this request here because I am working on adding c-lightning support to my project [Polar](https://github.com/jamaljsr/polar). I am using this library to communicate with the nodes. In order to display the network graph consistently with directional channels, I need to know which node opened the channel originally.

**Comment by saubyk** [comment]
Hi @jamaljsr 
There is a `direction` flag in the listpeers output, which we can use. Although, I am not entirely convinced if that flag correctly reflects which peer opened the channel.

I tried testing with my node, where I opened a channel from the node and opened another channel to the node, in both the cases it set flag to 1.

This might be the relevant code where this flag is being set in c-lightning:
https://github.com/ElementsProject/lightning/blob/4e8141aa36e38b0e2b746fc0ed990af16b77a83d/bitcoin/short_channel_id.h

Nonetheless, let me add that flag to the API output. You can test and let me know if its correctly reflecting the scenarios.

**Comment by jamaljsr** [comment]
Haha, I was working on a PR while you responded.

Yes, you are correct. I forked the repo and added the `initiator` field based on the `peer.channels[0].direction` flag. I tested it with a local regtest network and can confirm it works as expected. It's `true` when the c-lightning node opened the channel and `false` otherwise. I even tested with a mix of c-lightning/LND nodes.

Thanks for the reply. You can use my PR if it makes your life easier.

**Comment by saubyk** [comment]
@jamaljsr merged your PR, with a few tweaks. It should work per your expectation.

Thanks :-) 👍
