### ISSUE TITLE
C-lightning deprecations

### ISSUE THREAD

**Issue by darosior** [Ride-The-Lightning/c-lightning-REST#35]
Hi,

For your interest https://github.com/ElementsProject/lightning/pull/3603 removes some fields in the API which have been deprecated for several (6 iirc) months.

Namely:
- The `description` field in `sendpay`.
- The `satoshi` field in `fundchannel_start` (now `amount`). Note also this commit https://github.com/ElementsProject/lightning/pull/3603/commits/49e21538cc99e8f7340d174f02b853cc582dfd2a .
- No more `localfeatures` and `globalfeatures` fields in `listnodes`, `listpeers`, `peer_connected`.
- No more `force` bool in `close`.

Since now RTL relies on your wrapper, just wanted you to know ! :smiley:

**Comment by saubyk** [comment]
@darosior thanks for letting me know.

**Comment by rustyrussell** [comment]
Note: you should always test with "enable-deprecated-apis=false" (but ship without that!) so you'll find things when we deprecate it, not 6 months later when we remove it!

**Comment by saubyk** [comment]
@jamaljsr @kaloudis @ShahanaFarooqui 
Please note the deprecations above. These fields will be removed from c-lightning v0.8.2.
Please plan to remove these fields from your respective UIs if you are using them.

**Comment by jamaljsr** [comment]
@saubyk thanks for the heads up 👍

**Comment by saubyk** [comment]
Closing this ticket. As deprecations are addressed.
