### ISSUE TITLE
Does this expose lightning-cli in its entirety?

### ISSUE THREAD

**Issue by Fonta1n3** [Ride-The-Lightning/c-lightning-REST#48]
Just wondering if this only exposes limited functionality or if it exposes the entire suite of rpc commands? TIA.

**Comment by saubyk** [comment]
Hi @Fonta1n3 the current command coverage is documented [here](https://github.com/Ride-The-Lightning/c-lightning-REST/blob/master/docs/CLTCommandCoverage.md)

The functionality currently exposed is limited, primarily driven by the needs of RTL, Zeus or Polar projects. If you need more commands covered, I can definitely add or except a PR for the same. :-)
The API exposed are documented [here](https://github.com/Ride-The-Lightning/c-lightning-REST#apis). Swagger documentation is also available with the API server.

**Comment by Fonta1n3** [comment]
@saubyk Thanks for the prompt response! I am in very active development right now so don’t have a complete set of commands yet. Will get back to you when i do 👍

**Comment by saubyk** [comment]
No worry, feel free to open an issue if you need APIs for any command, which is not covered yet.
