### ISSUE TITLE
Add and use rest-cert-cn to the config.

### ISSUE THREAD

**Issue by dscotese** [Ride-The-Lightning/c-lightning-REST#51]
If I understand the security of using https instead of http, I think allowing the user to tell CLRest what the CN property of the self-signed certificate is makes sense.  Currently, it defaults to "localhost" and the instance of Zeus LN on my mobile gets an error that the IP address of my node is not the CN of the certificate: 
```
Error: Hostname (my node's IP address) NOT verified:
    certificate: sha256/...=
    DN: CN=localhost,O=baz...
    subjectAltNames: []
```
Am I interpreting this error correctly?

Is it possible for the plugin to create the self-signed certificate using a value supplied in the config for `subj '/CN=localhost'`?  If so, the default self-signed certificate would then be useful on remote devices that the public key without making other adjustments.

**Comment by willcl-ark** [comment]
This patch adds `DOMAIN` to the config, which allows you to specify a domain to the certificate in the `subjectAltNames`

```
diff --git a/cl-rest.js b/cl-rest.js
index f8f1a56..3e9a87a 100644
--- a/cl-rest.js
+++ b/cl-rest.js
@@ -28,6 +28,7 @@ if (!config.PORT || !config.DOCPORT || !config.PROTOCOL || !config.EXECMODE)
 const PORT = config.PORT;
 const EXECMODE = config.EXECMODE;
 const DOCPORT = config.DOCPORT;
+const DOMAIN = config.DOMAIN || "localhost";

 //Create certs folder
 try {
@@ -44,7 +45,7 @@ if ( ! fs.existsSync( key ) || ! fs.existsSync( certificate ) ) {
     try {
         execSync( 'openssl version', execOptions );
         execSync(
-            `openssl req -x509 -newkey rsa:2048 -keyout ./certs/key.tmp.pem -out ${ certificate } -days 365 -nodes -subj "/C=US/ST=Foo/L=Bar/O=Baz/CN=localhost"`,
+            `openssl req -x509 -newkey rsa:2048 -keyout ./certs/key.tmp.pem -out ${ certificate } -days 365 -nodes -subj "/C=US/ST=Foo/L=Bar/O=Baz/CN=c-lightning-rest" --addext "subjectAltName = DNS:${ DOMAIN }"`,
             execOptions
         );
         execSync( `openssl rsa -in ./certs/key.tmp.pem -out ${ key }`, execOptions );
@@ -155,4 +156,4 @@ process.on('SIGTERM', () => {
     server.close();
     docserver.close();
     process.exit(0);
-})
\ No newline at end of file
+})
diff --git a/sample-cl-rest-config.json b/sample-cl-rest-config.json
index a521726..2a96b8c 100644
--- a/sample-cl-rest-config.json
+++ b/sample-cl-rest-config.json
@@ -3,5 +3,6 @@
     "DOCPORT": 4001,
     "PROTOCOL": "https",
     "EXECMODE": "production",
-    "RPCCOMMANDS": ["*"]
+    "RPCCOMMANDS": ["*"],
+    "DOMAIN": "localhost"
 }
```

**Comment by dscotese** [comment]
I like the idea, and I don't understand enough to predict whether or not it solves the problem I encountered.  Your patch would need an update to the documentation (or, even better, the process of connecting Zeus to a node) to indicate that the user might need to add "DOMAIN" to the config (I don't remember doing it) in order to use the self-signed certificate in situations like mine.

**Comment by willcl-ark** [comment]
@dscotese I added as a PR (includes doc and sample config) here so some regular contributors can take a look, but it works for me(TM), solving the same issue as you with Zeus (although Zeus did require a bit of removing server, force closing and adding as a new server to work)  https://github.com/Ride-The-Lightning/c-lightning-REST/pull/87

Now that you mention it though, I think for users _upgrading_ it will still simply detect the old certs and not regerate them 🤔 Probably should either add docs for that or somehow have it auto upgrade. Either way a new macaroon and cert would result, and subsequent certificate re-install would be needed.

**Comment by saubyk** [comment]
Merged into the release branch.
