### ISSUE TITLE
Open channel: Include sat/vbyte fee estimate with Slow/Normal/Urgent options

### ISSUE THREAD

**Issue by billygarrison** [Ride-The-Lightning/c-lightning-REST#53]
It would be nice if beside "Slow" it included the fee that would be used. For example, if the mempool is full and "Slow" means 50 sats/vbyte then I would likely wait to open the channel.

![image](https://user-images.githubusercontent.com/30005204/102720553-70037080-42cb-11eb-938b-2607b8fb662c.png)

**Comment by saubyk** [comment]
Hi @billygarrison, will handle this in RTL instead.

**Comment by billygarrison** [comment]
Hmm sorry @saubyk ... I thought I was in the RTL repo !

**Comment by saubyk** [comment]
This requirement will be addressed in the next RTL release v0.11.1.
