### ISSUE TITLE
Private channel can't be opened

### ISSUE THREAD

**Issue by bolatovumar** [Ride-The-Lightning/c-lightning-REST#55]
See this line:
https://github.com/Ride-The-Lightning/c-lightning-REST/blob/22bb6c34960d09b8ec3c834a606b863446a3ef4f/controllers/channel.js#L77

It double-bangs the input for the `announce` field which controls if a private channel should be opened. Since it double-bangs inputs for `'0'` and `'false'` the resulting boolean will always be equal tor `true` so the channel will always be public.

**Comment by saubyk** [comment]
@bolatovumar should be good now. Thanks for the pointing it out and the PR.
