### ISSUE TITLE
Security Concern

### ISSUE THREAD

**Issue by crabel99** [Ride-The-Lightning/c-lightning-REST#62]
The API opens access to `lightning-rpc` allowing uncredentialed access on the local machine into those ports. If a user were to become compromised an attacker would have direct access into `lightning-rpc`. Would be better if we could control access to the REST API uri's, either through a permissioned unix domain socket or through token authentication over https.

**Comment by saubyk** [comment]
The access to the Apis is not uncredentialed. An `access.macaroon` token is generated when the server is initiated. That token has to be passed to the APIs to enable access.

**Comment by crabel99** [comment]
It took me a bit, found it in the documentation... sorry about the false alarm.
