### ISSUE TITLE
plugin dies in c-lightning if failed payment

### ISSUE THREAD

**Issue by rbckman** [Ride-The-Lightning/c-lightning-REST#89]
c-lightning-REST dies if payment fails

UNUSUAL plugin-plugin.js: Killing plugin: Failed to parse JSON response 'SyntaxError: Unexpected token { in JSON at position 888?    at JSON.parse (<anonymous>)?    at Plugin._mainLoop (/home/madbaker/c-lightning-REST/node_modules/clightningjs/src/plugin.js:164:20)?    at Socket.<anonymous> (/home/madbaker/c-lightning-REST/node_modules/clightningjs/src/plugin.js:209:12)?    at Socket.emit (events.js:314:20)?    at emitReadable_ (_stream_readable.js:557:12)?    at processTicksAndRejections (internal/process/task_queues.js:83:21)?SyntaxError: Unexpected token { in JSON at position 888?    at JSON.parse (<anonymous>)?    at Plugin._mainLoop (/home/madbaker/c-lightning-REST/node_modules/clightningjs/src/plugin.js:164:20)?    at Socket.<anonymous> (/home/madbaker/c-lightning-REST/node_modules/clightningjs/src/plugin.js:209:12)?    at Socket.emit (events.js:314:20)?    at emitReadable_ (_stream_readable.js:557:12)?    at processTicksAndRejections (internal/process/task_queues.js:83:21)?{"jsonrpc":"2.0","method":"log","params":{"level":"warn","message":"{\"type\":\"lightning\",\"message\":\"Ran out of routes to try after 62 attempts: see `paystatus`\",\"name\":\"LightningError\",\"code\":210,\"attempts\":[{\"status\":\"failed\",\"failreason\":\"failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)\",\"partid\":1,\"amount\":\"1000000msat\"},{\"status\":\"failed\",\"failreason\":\"failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)\",\"partid\":2,\"amount\":\"1000000msat\",\"parent_partid\":1},{\"status\":\"failed\",\"failreason\":\"failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)\",\"partid\":3,\"amount\":\"1000000msat\",\"parent_partid\":2},{\"status\":\"failed\",\"failreason\":\"failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)\",\"partid\":4,\"amount\":\"1000000msat\",\"parent_partid\":3},{\"status\":\"failed\",\"failreason\":\"failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)\",\"partid\":5,\"amount\":\"1000000msat\",\"parent_partid\":4},{\"status\":\"failed\",\"failreason\":\"failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)\",\"partid\":6'

**Comment by saubyk** [comment]
Hi @rbckman can you please verify if this is still an issue with the latest release of c-lightning? thanks.

**Comment by saubyk** [comment]
pr merged into the release branch
